# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"/\n\x0cImageFileReq\x12\x11\n\ttime_sent\x18\x01 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\"\n\rImageFileRecv\x12\x11\n\ttime_recv\x18\x01 \x01(\x01\"\x0c\n\nPingServer\"\x1f\n\nPingClient\x12\x11\n\ttime_sent\x18\x01 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEFILEREQ._serialized_start=16
  _IMAGEFILEREQ._serialized_end=63
  _IMAGEFILERECV._serialized_start=65
  _IMAGEFILERECV._serialized_end=99
  _PINGSERVER._serialized_start=101
  _PINGSERVER._serialized_end=113
  _PINGCLIENT._serialized_start=115
  _PINGCLIENT._serialized_end=146
# @@protoc_insertion_point(module_scope)
