# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\"P\n\x0cImageFileReq\x12\x16\n\ttime_sent\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\x0c\n\n_time_sentB\x07\n\x05_data\"5\n\rImageFileRecv\x12\x16\n\ttime_recv\x18\x01 \x01(\x01H\x00\x88\x01\x01\x42\x0c\n\n_time_recvb\x06proto3'
)




_IMAGEFILEREQ = _descriptor.Descriptor(
  name='ImageFileReq',
  full_name='ImageFileReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_sent', full_name='ImageFileReq.time_sent', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ImageFileReq.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_time_sent', full_name='ImageFileReq._time_sent',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_data', full_name='ImageFileReq._data',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=96,
)


_IMAGEFILERECV = _descriptor.Descriptor(
  name='ImageFileRecv',
  full_name='ImageFileRecv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_recv', full_name='ImageFileRecv.time_recv', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_time_recv', full_name='ImageFileRecv._time_recv',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=98,
  serialized_end=151,
)

_IMAGEFILEREQ.oneofs_by_name['_time_sent'].fields.append(
  _IMAGEFILEREQ.fields_by_name['time_sent'])
_IMAGEFILEREQ.fields_by_name['time_sent'].containing_oneof = _IMAGEFILEREQ.oneofs_by_name['_time_sent']
_IMAGEFILEREQ.oneofs_by_name['_data'].fields.append(
  _IMAGEFILEREQ.fields_by_name['data'])
_IMAGEFILEREQ.fields_by_name['data'].containing_oneof = _IMAGEFILEREQ.oneofs_by_name['_data']
_IMAGEFILERECV.oneofs_by_name['_time_recv'].fields.append(
  _IMAGEFILERECV.fields_by_name['time_recv'])
_IMAGEFILERECV.fields_by_name['time_recv'].containing_oneof = _IMAGEFILERECV.oneofs_by_name['_time_recv']
DESCRIPTOR.message_types_by_name['ImageFileReq'] = _IMAGEFILEREQ
DESCRIPTOR.message_types_by_name['ImageFileRecv'] = _IMAGEFILERECV
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageFileReq = _reflection.GeneratedProtocolMessageType('ImageFileReq', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFILEREQ,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ImageFileReq)
  })
_sym_db.RegisterMessage(ImageFileReq)

ImageFileRecv = _reflection.GeneratedProtocolMessageType('ImageFileRecv', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFILERECV,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:ImageFileRecv)
  })
_sym_db.RegisterMessage(ImageFileRecv)


# @@protoc_insertion_point(module_scope)
